spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    hikari:
      username: dongju
      jdbc-url: jdbc:mysql://localhost:3306/study
      driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG